/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.NGOAdmin;
import Business.WorkQueue.NGOFundRequest;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.DirectorOrgNGO;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MALLESH
 */
public class NGOAdminProcessWRJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
private JPanel containerPanel;
private UserAccount currentUser;
private NGOFundRequest ngoFundRequestSelected;
private Enterprise enterpriseRef;

    public NGOAdminProcessWRJPanel(JPanel containerPanel, UserAccount currentUser, NGOFundRequest selectedRequest, Enterprise enterpriseRef) {
        initComponents();
        this.containerPanel = containerPanel;
    this.currentUser = currentUser;
    this.ngoFundRequestSelected = selectedRequest;
    this.enterpriseRef = enterpriseRef;

    amountNeededTxt.setText(String.valueOf(ngoFundRequestSelected.getRequestedFundAmount()));
    hospitalNameTxt.setText(ngoFundRequestSelected.getHospitalName());
    hospitalAddressTxt.setText(ngoFundRequestSelected.getHospitalLocation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountNeededTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        messageTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sendRequestToDirectoryJBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hospitalNameTxt = new javax.swing.JTextField();
        hospitalAddressTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rejectJBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        amountNeededTxt.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Amount Needed:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Message:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("NGO Admin Request Process work Area ");

        sendRequestToDirectoryJBtn.setBackground(new java.awt.Color(153, 255, 153));
        sendRequestToDirectoryJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sendRequestToDirectoryJBtn.setText("Send to Director for approval");
        sendRequestToDirectoryJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestToDirectoryJBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Hospital Name:");

        hospitalNameTxt.setEnabled(false);

        hospitalAddressTxt.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Hospital Address:");

        rejectJBtn.setBackground(new java.awt.Color(255, 51, 51));
        rejectJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rejectJBtn.setText("Reject");
        rejectJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJBtnActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ngo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(backBtn)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addComponent(sendRequestToDirectoryJBtn))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(amountNeededTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hospitalAddressTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rejectJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendRequestToDirectoryJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rejectJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountNeededTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(messageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(247, 247, 247))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
    containerPanel.remove(this);
    Component[] components = containerPanel.getComponents();
    Component previousScreen = components[components.length - 1];

    NGOAdminWAJPanel ngoPanel = (NGOAdminWAJPanel) previousScreen;
    ngoPanel.populateRequestTable();

    CardLayout layout = (CardLayout) containerPanel.getLayout();
    layout.previous(containerPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void sendRequestToDirectoryJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestToDirectoryJBtnActionPerformed
        // TODO add your handling code here:
String message = messageTxt.getText().trim();
    if (message.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Message is mandatory!");
        return;
    }

    ngoFundRequestSelected.setRequestNote(message);

    int confirmation = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
    if (confirmation == JOptionPane.YES_OPTION) {

        ngoFundRequestSelected.setRequestSender(currentUser);
        ngoFundRequestSelected.setRequestStatus("Sent to Director");

        Organization targetOrg = null;
        for (Organization org : enterpriseRef.getOrgDir().getOrganizations()) {
            if (org instanceof DirectorOrgNGO) {
                targetOrg = org;
                break;
            }
        }

        if (targetOrg != null) {
            targetOrg.getWorkQueue().getWorkRequests().add(ngoFundRequestSelected);
            currentUser.getWorkQueue().getWorkRequests().add(ngoFundRequestSelected);
        }

        JOptionPane.showMessageDialog(null, "Request successfully sent to Director!");
        messageTxt.setText("");
        rejectJBtn.setEnabled(false);
        sendRequestToDirectoryJBtn.setEnabled(false);
    }
    }//GEN-LAST:event_sendRequestToDirectoryJBtnActionPerformed

    private void rejectJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJBtnActionPerformed
    String message = messageTxt.getText().trim();
    if (message.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Message is mandatory!");
        return;
    }

    ngoFundRequestSelected.setRequestNote(message);

    int confirmation = JOptionPane.showConfirmDialog(null, "Do you want to reject?");
    if (confirmation == JOptionPane.YES_OPTION) {

        ngoFundRequestSelected.setRequestStatus("Rejected");

        JOptionPane.showMessageDialog(null, "Request has been rejected!");
        messageTxt.setText("");
        rejectJBtn.setEnabled(false);
        sendRequestToDirectoryJBtn.setEnabled(false);
    }
    }//GEN-LAST:event_rejectJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountNeededTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField hospitalAddressTxt;
    private javax.swing.JTextField hospitalNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField messageTxt;
    private javax.swing.JButton rejectJBtn;
    private javax.swing.JButton sendRequestToDirectoryJBtn;
    // End of variables declaration//GEN-END:variables
}
